<?php
// module/Album/view/album/album/add.phtml:
 
$title = 'Add new Site';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('url', array('action' => 'add')));
$form->prepare();
 
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('real_site'));
//echo $this->formRow($form->get('captcha'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();